package com.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public OrderInfo() {
	}

	@org.kie.api.definition.type.Label("order id")
	private long orderId;
	@org.kie.api.definition.type.Label("item name")
	private java.lang.String item;
	@org.kie.api.definition.type.Label("category")
	private java.lang.String category;
	@org.kie.api.definition.type.Label("urgency")
	private java.lang.String urgency;

	@org.kie.api.definition.type.Label("price")
	private double price;
	@org.kie.api.definition.type.Label("approved")
	private Boolean managerApproval;
	@org.kie.api.definition.type.Label("rejection reason")
	private String rejectionReason;

	public OrderInfo(long orderId, java.lang.String item,
			java.lang.String category, java.lang.String urgency, double price,
			java.lang.Boolean managerApproval, java.lang.String rejectionReason) {
		this.orderId = orderId;
		this.item = item;
		this.category = category;
		this.urgency = urgency;
		this.price = price;
		this.managerApproval = managerApproval;
		this.rejectionReason = rejectionReason;
	}

}