package com.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public OrderInfo() {
	}

	@org.kie.api.definition.type.Label("order id")
	private long orderId;
	@org.kie.api.definition.type.Label("item name")
	private java.lang.String item;
	@org.kie.api.definition.type.Label("category")
	private java.lang.String category;
	@org.kie.api.definition.type.Label("urgency")
	private java.lang.String urgency;

	@org.kie.api.definition.type.Label("price")
	private double price;
	@org.kie.api.definition.type.Label("approved")
	private Boolean managerApproval;
	@org.kie.api.definition.type.Label("rejection reason")
	private String rejectionReason;

	public OrderInfo(long orderId, java.lang.String item, java.lang.String category, java.lang.String urgency,
			double price, java.lang.Boolean managerApproval, java.lang.String rejectionReason) {
		this.orderId = orderId;
		this.item = item;
		this.category = category;
		this.urgency = urgency;
		this.price = price;
		this.managerApproval = managerApproval;
		this.rejectionReason = rejectionReason;
	}

	@Override
	public String toString() {
		return String.format(
				"OrderInfo [orderId=%s, item=%s, category=%s, urgency=%s, price=%s, managerApproval=%s, rejectionReason=%s]",
				orderId, item, category, urgency, price, managerApproval, rejectionReason);
	}

	public long getOrderId() {
		return orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public java.lang.String getItem() {
		return item;
	}

	public void setItem(java.lang.String item) {
		this.item = item;
	}

	public java.lang.String getCategory() {
		return category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public java.lang.String getUrgency() {
		return urgency;
	}

	public void setUrgency(java.lang.String urgency) {
		this.urgency = urgency;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Boolean getManagerApproval() {
		return managerApproval;
	}

	public void setManagerApproval(Boolean managerApproval) {
		this.managerApproval = managerApproval;
	}

	public String getRejectionReason() {
		return rejectionReason;
	}

	public void setRejectionReason(String rejectionReason) {
		this.rejectionReason = rejectionReason;
	}
}