package com.example;

import javax.persistence.ElementCollection;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class OrderInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("order id")
	private long orderId;
	@org.kie.api.definition.type.Label("item name")
	private java.lang.String item;
	@org.kie.api.definition.type.Label("category")
	private java.lang.String category;
	@org.kie.api.definition.type.Label("urgency")
	private java.lang.String urgency;

	@org.kie.api.definition.type.Label("price")
	private double price;
	@org.kie.api.definition.type.Label("approved")
	private Boolean managerApproval;
	@org.kie.api.definition.type.Label("rejection reason")
	private String rejectionReason;
	@org.kie.api.definition.type.Description("suppliers list to involve")
	@org.kie.api.definition.type.Label("suppliers list")
	@ElementCollection
	private java.util.List<java.lang.String> suppliersList;
	@org.kie.api.definition.type.Label("target price")
	private double targetPrice;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ORDERINFO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "ORDERINFO_ID_SEQ", name = "ORDERINFO_ID_GENERATOR")
	private java.lang.Long id;

	public OrderInfo() {
	}

	public OrderInfo(java.util.List<java.lang.String> suppliersList,
			double targetPrice, long orderId, java.lang.String item,
			java.lang.String category, java.lang.String urgency, double price,
			java.lang.Boolean managerApproval, java.lang.String rejectionReason) {
		this.suppliersList = suppliersList;
		this.targetPrice = targetPrice;
		this.orderId = orderId;
		this.item = item;
		this.category = category;
		this.urgency = urgency;
		this.price = price;
		this.managerApproval = managerApproval;
		this.rejectionReason = rejectionReason;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */

	@Override
	public String toString() {
		return String
				.format("OrderInfo {category: %s, item: %s, managerApproval: %s, orderId: %s, price: %s, rejectionReason: %s, suppliersList: %s, targetPrice: %s, urgency: %s }",
						category, item, managerApproval, orderId, price,
						rejectionReason, suppliersList, targetPrice, urgency);
	}

	public long getOrderId() {
		return orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public java.lang.String getItem() {
		return item;
	}

	public void setItem(java.lang.String item) {
		this.item = item;
	}

	public java.lang.String getCategory() {
		return category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public java.lang.String getUrgency() {
		return urgency;
	}

	public void setUrgency(java.lang.String urgency) {
		this.urgency = urgency;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Boolean getManagerApproval() {
		return managerApproval;
	}

	public void setManagerApproval(Boolean managerApproval) {
		this.managerApproval = managerApproval;
	}

	public String getRejectionReason() {
		return rejectionReason;
	}

	public void setRejectionReason(String rejectionReason) {
		this.rejectionReason = rejectionReason;
	}

	public java.util.List<java.lang.String> getSuppliersList() {
		return this.suppliersList;
	}

	public void setSuppliersList(java.util.List<java.lang.String> suppliersList) {
		this.suppliersList = suppliersList;
	}

	public double getTargetPrice() {
		return this.targetPrice;
	}

	public void setTargetPrice(double targetPrice) {
		this.targetPrice = targetPrice;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public OrderInfo(long orderId, java.lang.String item,
			java.lang.String category, java.lang.String urgency, double price,
			java.lang.Boolean managerApproval,
			java.lang.String rejectionReason,
			java.util.List<java.lang.String> suppliersList, double targetPrice,
			java.lang.Long id) {
		this.orderId = orderId;
		this.item = item;
		this.category = category;
		this.urgency = urgency;
		this.price = price;
		this.managerApproval = managerApproval;
		this.rejectionReason = rejectionReason;
		this.suppliersList = suppliersList;
		this.targetPrice = targetPrice;
		this.id = id;
	}
}