package com.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SupplierInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	@org.kie.api.definition.type.Label("user")
	private java.lang.String user;
	@org.kie.api.definition.type.Label("best offer")
	private double offer;
	@org.kie.api.definition.type.Label("delivery date")
	private java.util.Date deliveryDate;
	@org.kie.api.definition.type.Label("selected")
	private boolean selected;

	public SupplierInfo() {
	}

	public SupplierInfo(java.lang.String user, double offer, java.util.Date deliveryDate, boolean selected) {
		this.user = user;
		this.offer = offer;
		this.deliveryDate = deliveryDate;
		this.selected = selected;
	}

	@Override
	public String toString() {
		return String.format("SupplierInfo [user=%s, offer=%s, deliveryDate=%s, selected=%s]", user, offer,
				deliveryDate, selected);
	}

	public java.lang.String getUser() {
		return user;
	}

	public void setUser(java.lang.String user) {
		this.user = user;
	}

	public double getOffer() {
		return offer;
	}

	public void setOffer(double offer) {
		this.offer = offer;
	}

	public java.util.Date getDeliveryDate() {
		return deliveryDate;
	}

	public void setDeliveryDate(java.util.Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}

}